Update .bash_profile and .bashrc to use absolute paths for source_relative_once
Add new utility functions to .bashrc

Update .envconfig to source prepend_path.bash

Modify .pathconfig to use absolute paths and add error handling for exclude_path

Update .profile to use absolute paths for sourcing functions

Refactor bin/apfs-dedup to use 'successful' instead of 'success?'

Update bin/apply-hooks to source utility_functions.bash with absolute path

Refactor bin/ask to use absolute paths for sourcing functions

Update bin/ask_local to use absolute path for sourcing ask

Refactor bin/clip to use absolute paths for sourcing functions

Update bin/datetimestamp to use absolute paths for sourcing functions

Refactor bin/functions/assert.bash to use absolute path for sourcing

diff --git a/bin/apfs-dedup b/bin/apfs-dedup
--- a/bin/apfs-dedup
+++ b/bin/apfs-dedup
@@ -2,9 +2,8 @@
 
 # set -euo pipefail
 
-success? () {
+successful() {
   "$@" > /dev/null 2>&1;
-  return $?
 }
 
 # Parse command-line arguments
@@ -122,15 +121,15 @@ while [[ $# -gt 0 ]]; do
 done
 
 # Dependencies check
-success? gum -v || { echo "Error: 'gum' is required."; exit 1; }
-success? xxhsum -V || { echo "Error: 'xxHash' is required."; exit 1; }
+successful gum -v || { echo "Error: 'gum' is required."; exit 1; }
+successful xxhsum -V || { echo "Error: 'xxHash' is required."; exit 1; }
 NUMFMT=gnumfmt
-if success? numfmt --version; then
+if successful numfmt --version; then
   NUMFMT=numfmt
 fi
-success? $NUMFMT --version || { echo "Error: 'numfmt' or 'gnumfmt' is required."; exit 1; }
+successful $NUMFMT --version || { echo "Error: 'numfmt' or 'gnumfmt' is required."; exit 1; }
 export NUMFMT
-success? gcc -v || { echo "Error: 'gcc' is required."; exit 1; }
+successful gcc -v || { echo "Error: 'gcc' is required."; exit 1; }
 
 # Function to check if two files are cloned on APFS
 # Returns 0 (true) if they are cloned, 1 (false) if not
