Updates, bugfixes and optimizations to dotfiles and PROMPT_COMMAND config

diff --git a/bin/apply-hooks b/bin/apply-hooks
--- a/bin/apply-hooks
+++ b/bin/apply-hooks
@@ -23,11 +23,11 @@ declare -a PROMPT_ARRAY
 inspect() {
 	local var
 	local output=""
-	
+
 	for var in "$@"; do
 		if declare -p "$var" &>/dev/null; then
 			local decl=$(declare -p "$var" 2>&1)
-			
+
 			case "$decl" in
 				"declare -a"*)
 					# Regular array
@@ -91,7 +91,7 @@ inspect() {
 			output+="unset $var; "
 		fi
 	done
-	
+
 	echo "$output"
 }
 
@@ -121,38 +121,83 @@ report_prompt_commands() {
 ##### Guix integration
 # [[ -s "$HOME/.guix-profile/etc/profile" ]] && source "$HOME/.guix-profile/etc/profile"
 
+BASH_PREEXEC_LOCATION="$HOME/dotfiles/lib/bash-preexec.sh"
+
+# Declare associative array to track initializer types
+declare -A initializer_types
+
+# Set known initializer types
+initializer_types["direnv hook bash"]="produces_code_to_run"
+initializer_types["mcfly init bash"]="produces_code_to_run"
+initializer_types["zoxide init --cmd cd --hook pwd bash"]="produces_code_to_run"
+initializer_types["wezterm_status_support"]="runs_code"
+initializer_types["starship init bash"]="produces_code_to_run"
+initializer_types["set_up_osc7_home"]="runs_code"
+initializer_types["cat '$BASH_PREEXEC_LOCATION'"]="produces_code_to_run"
+
 wrap_prompt_command_initializer() {
 	local initializer_cmd="$1"
-	local initializer_code=""
+	local initializer_type="${initializer_types[$initializer_cmd]:-"unknown"}"
 	local initializer_code_return_code=0
+
 	report_prompt_commands "before" "$initializer_cmd"
-	initializer_code=$(eval "$initializer_cmd")
-	initializer_code_return_code=$?
-	if [ -z "$initializer_code" ] && [ $initializer_code_return_code -eq 0 ]; then
-		# If the initializer code returned nothing and didn't error,
-		# then $initializer_cmd was actually meant to be run
-		# in the current context, instead of in a subshell generating the code to run
-		# (yes, this gets confusing...)
-		# Note that this is suboptimal since we are running it TWICE,
-		# but there's no other way to know without doing code analysis
+
+	if [[ "$initializer_type" == "runs_code" ]]; then
+		# The initializer runs code directly
 		eval "$initializer_cmd"
 		initializer_code_return_code=$?
-		truthy DEBUG_PROMPT_COMMANDS && echo "Ran '$initializer_cmd'"
-	elif ! [ -z "$initializer_code" ]; then
-		# if the initializer code generated MORE code, then run that code in
-		# the current context
-		eval "$initializer_code"
+		truthy DEBUG_PROMPT_COMMANDS && echo "Ran '$initializer_cmd' directly"
+
+	elif [[ "$initializer_type" == "produces_code_to_run" ]]; then
+		# The initializer produces code that should be evaluated
+		local initializer_code
+		initializer_code=$(eval "$initializer_cmd")
 		initializer_code_return_code=$?
-		truthy DEBUG_PROMPT_COMMANDS && echo "Ran the code generated by '$initializer_cmd'"
+
+		if [[ $initializer_code_return_code -eq 0 ]]; then
+			eval "$initializer_code"
+			initializer_code_return_code=$?
+			truthy DEBUG_PROMPT_COMMANDS && echo "Ran the code generated by '$initializer_cmd'"
+		else
+			echo "Error: Initializer '$initializer_cmd' failed with error code $initializer_code_return_code" >&2
+			return $initializer_code_return_code
+		fi
+
 	else
-		echo "Error: Initializer '$initializer_cmd' returned nothing and an error code of $initializer_code_return_code" >&2
-		return $initializer_code_return_code
+		# For unknown initializers, try to detect type (fallback to old behavior)
+		echo "Warning: Unknown initializer type for '$initializer_cmd', trying to detect type" >&2
+
+		local initializer_code
+		initializer_code=$(eval "$initializer_cmd")
+		initializer_code_return_code=$?
+
+		if [ -z "$initializer_code" ] && [ $initializer_code_return_code -eq 0 ]; then
+			# If it returned nothing successfully, it was meant to be run directly
+			eval "$initializer_cmd"
+			initializer_code_return_code=$?
+			truthy DEBUG_PROMPT_COMMANDS && echo "Detected and ran '$initializer_cmd' directly"
+			# Record this type for future use
+			initializer_types["$initializer_cmd"]="runs_code"
+		elif ! [ -z "$initializer_code" ]; then
+			# If it returned code, evaluate that code
+			eval "$initializer_code"
+			initializer_code_return_code=$?
+			truthy DEBUG_PROMPT_COMMANDS && echo "Detected and ran code generated by '$initializer_cmd'"
+			# Record this type for future use
+			initializer_types["$initializer_cmd"]="produces_code_to_run"
+		else
+			echo "Error: Initializer '$initializer_cmd' returned nothing and an error code of $initializer_code_return_code" >&2
+			return $initializer_code_return_code
+		fi
 	fi
+
+	# Handle PROMPT_COMMAND updates
 	if [[ -n "$PROMPT_COMMAND" ]]; then
 		truthy DEBUG_PROMPT_COMMANDS && echo "Adding '$PROMPT_COMMAND' to PROMPT_ARRAY"
 		PROMPT_ARRAY+=("$PROMPT_COMMAND")
 		truthy DEBUG_PROMPT_COMMANDS && echo "PROMPT_ARRAY is now: ${PROMPT_ARRAY[@]}"
 	fi
+
 	report_prompt_commands "after" "$initializer_cmd"
 	return $initializer_code_return_code
 }
@@ -170,14 +215,14 @@ wrap_prompt_command_initializer() {
 #   if [[ "$(declare -p PROMPT_COMMAND 2>&1)" == "declare -a"* ]]; then
 #     # Add the current PROMPT_COMMAND array to precmd_functions
 #     precmd_functions+=("${PROMPT_COMMAND[@]}")
-		
+
 #     # Set PROMPT_COMMAND to empty string
 #     # unset PROMPT_COMMAND # since the following line won't erase its array type (!)
 #     # PROMPT_COMMAND=""
-		
+
 #     # Run the initializer
 #     eval "$($initializer_cmd)"
-		
+
 #     # Check if PROMPT_COMMAND is still a string (not an array)
 #     if ! [[ "$(declare -p PROMPT_COMMAND 2>&1)" == "declare -a"* ]]; then
 #       # Get the string value and append it as array elements to a new PROMPT_COMMAND
@@ -295,17 +340,24 @@ set_up_osc7_home() {
 # You'll want to pull down the file and add it to your bash profile/configuration (i.e ~/.bashrc, ~/.profile, ~/.bash_profile, etc).
 # It must be the last thing imported in your bash profile!
 # Pull down our file from GitHub and write it to your home directory as a hidden file.
-export BASH_PREEXEC_LOCATION="$HOME/dotfiles/lib/bash-preexec.sh"
+
 update_bash_preexec() {
 	[ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
 	mkdir -p ~/dotfiles/lib
 	curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o "$BASH_PREEXEC_LOCATION"
 }
+
+wezterm_status_support() {
+	PROMPT_COMMAND='printf "\e]7;file://%s%s\a" "$HOSTNAME" "$PWD"; '$PROMPT_COMMAND
+}
+
 # Run all initializers in the correct order
 # First, run tools that modify PROMPT_COMMAND directly
-command -v zoxide >/dev/null 2>&1 && wrap_prompt_command_initializer "zoxide init --cmd cd --hook pwd bash" || err "zoxide not found"
 command -v direnv >/dev/null 2>&1 && wrap_prompt_command_initializer "direnv hook bash" || err "direnv not found"
 command -v mcfly >/dev/null 2>&1 && wrap_prompt_command_initializer "mcfly init bash" || err "mcfly not found"
+if [ "$TERM_PROGRAM" = "WezTerm" ]; then
+	wrap_prompt_command_initializer "wezterm_status_support"
+fi
 
 # Then run starship which uses precmd_functions
 command -v starship >/dev/null 2>&1 && wrap_prompt_command_initializer "starship init bash" || err "starship not found"
@@ -313,18 +365,24 @@ command -v starship >/dev/null 2>&1 && wrap_prompt_command_initializer "starship
 # Run any custom hooks
 wrap_prompt_command_initializer "set_up_osc7_home"
 
+wrap_prompt_command_initializer "cat '$BASH_PREEXEC_LOCATION'" || err "bash-preexec not found"
+
+command -v zoxide >/dev/null 2>&1 && wrap_prompt_command_initializer "zoxide init --cmd cd --hook pwd bash" || err "zoxide not found"
+
 # Source bash-preexec LAST to ensure it can see all hooks
-if [ -f "$BASH_PREEXEC_LOCATION" ]; then
-	# Source bash-preexec directly to ensure it works properly
-	source "$BASH_PREEXEC_LOCATION" || \
-		echo -e "Problem when setting up bash_preexec config from ${BASH_PREEXEC_LOCATION}; it errored.\n You may need to run update_bash_preexec to fix this."
-	# Ensure precmd_functions are properly registered
-	if [[ "$(declare -p precmd_functions 2>&1)" == "declare -a"* ]] && [[ "${#precmd_functions[@]}" -gt 0 ]]; then
-		truthy DEBUG_PROMPT_COMMANDS && echo "Registered ${#precmd_functions[@]} precmd functions with bash-preexec"
-	fi
-else
-	echo -e "Problem when setting up bash_preexec config from ${BASH_PREEXEC_LOCATION}; it is nonexistent.\n You may need to run update_bash_preexec to fix this."
-fi
+# [ -f "$BASH_PREEXEC_LOCATION" ] && source "$BASH_PREEXEC_LOCATION" || err "bash-preexec not found"
+
+# if [ -f "$BASH_PREEXEC_LOCATION" ]; then
+# 	# Source bash-preexec directly to ensure it works properly
+# 	source "$BASH_PREEXEC_LOCATION" || \
+# 		echo -e "Problem when setting up bash_preexec config from ${BASH_PREEXEC_LOCATION}; it errored.\n You may need to run update_bash_preexec to fix this."
+# 	# Ensure precmd_functions are properly registered
+# 	if [[ "$(declare -p precmd_functions 2>&1)" == "declare -a"* ]] && [[ "${#precmd_functions[@]}" -gt 0 ]]; then
+# 		truthy DEBUG_PROMPT_COMMANDS && echo "Registered ${#precmd_functions[@]} precmd functions with bash-preexec"
+# 	fi
+# else
+# 	echo -e "Problem when setting up bash_preexec config from ${BASH_PREEXEC_LOCATION}; it is nonexistent.\n You may need to run update_bash_preexec to fix this."
+# fi
 
 # and then force PROMPT_COMMAND to just be the bash_preexec hook
 # PROMPT_COMMAND=([0]="__bp_precmd_invoke_cmd" [1]="__bp_interactive_mode")
