MASSIVE DOTFILE UPDATE. Mostly moved functions to script files in bin/. But also made way more changes. /shrug

diff --git a/bin/apply-hooks b/bin/apply-hooks
--- a/bin/apply-hooks
+++ b/bin/apply-hooks
@@ -3,6 +3,104 @@
 [ -n "${DEBUG_SHELLCONFIG}" ] && echo "Entering $(echo "${BASH_SOURCE[0]}" | $SED "s|^$HOME|~|")"
 [ -n "${DEBUG_PATHCONFIG}" ] && echo "$PATH"
 
+##### rust cargo hook and related environment dependencies
+# [[ -s "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
+# needs rustc "curl https://sh.rustup.rs -sSf | sh"
+needs eza "cargo install eza"
+needs tokei "cargo install --git https://github.com/XAMPPRocky/tokei.git tokei"
+
+
+# start with a blank slate
+unset PROMPT_COMMAND
+unset precmd_functions
+unset preexec_functions
+unset PROMPT_ARRAY
+PROMPT_COMMAND=""
+declare -a precmd_functions
+declare -a preexec_functions
+declare -a PROMPT_ARRAY
+
+inspect() {
+	local var
+	local output=""
+	
+	for var in "$@"; do
+		if declare -p "$var" &>/dev/null; then
+			local decl=$(declare -p "$var" 2>&1)
+			
+			case "$decl" in
+				"declare -a"*)
+					# Regular array
+					if [[ "$decl" == *"$var=()"* ]]; then
+						# Empty array
+						output+="declare -a $var; "
+					else
+						# Check if array is declared but unset
+						if [[ "$decl" == "declare -a $var" ]]; then
+							output+="declare -a $var; "
+						else
+							# Array with values
+							local array_part=${decl#*$var=}
+							output+="$var=$array_part; "
+						fi
+					fi
+					;;
+				"declare -A"*)
+					# Associative array
+					if [[ "$decl" == *"$var=()"* ]]; then
+						# Empty associative array
+						output+="declare -A $var; "
+					else
+						# Check if associative array is declared but unset
+						if [[ "$decl" == "declare -A $var" ]]; then
+							output+="declare -A $var; "
+						else
+							# Associative array with values
+							local array_part=${decl#*$var=}
+							output+="$var=$array_part; "
+						fi
+					fi
+					;;
+				"declare -x"*)
+					if [[ "$decl" != *"=\""* ]]; then
+						# Exported without value
+						output+="export $var; "
+					else
+						# Exported with value
+						local value="${!var}"
+						output+="export $var=\"$value\"; "
+					fi
+					;;
+				"declare -i"*)
+					# Integer
+					local value="${!var}"
+					output+="$var=$value; "
+					;;
+				"declare -r"*)
+					# Readonly
+					local value="${!var}"
+					output+="readonly $var=\"$value\"; "
+					;;
+				*)
+					# Regular variable
+					local value="${!var}"
+					output+="$var=\"$value\"; "
+					;;
+			esac
+		else
+			output+="unset $var; "
+		fi
+	done
+	
+	echo "$output"
+}
+
+# DEBUG_PROMPT_COMMANDS=1
+report_prompt_commands() {
+	truthy DEBUG_PROMPT_COMMANDS && echo "$1 $2: $(inspect PROMPT_COMMAND precmd_functions preexec_functions PROMPT_ARRAY)"
+}
+
+
 # We start with a clean PROMPT_COMMAND and precmd_functions slate in the event we rehash (which used to screw this up)
 # unset PROMPT_COMMAND
 # unset precmd_functions
@@ -20,62 +118,127 @@
 # set -o pipefail
 # set -x
 
-source_relative_once $HOME/dotfiles/bin/functions/utility_functions.bash # to get array_contains_element
-
-needs() {
-  [ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
-  local bin="$1"
-  shift
-  command -v "$bin" >/dev/null 2>&1 || {
-    printf "%s is required but it's not installed or in PATH; %s\n" "$bin" "$*" >&2
-    return 1
-  }
-}
-
-##### rust cargo hook and related environment dependencies
-# [[ -s "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
-# needs rustc "curl https://sh.rustup.rs -sSf | sh"
-needs eza "cargo install eza"
-needs tokei "cargo install --git https://github.com/XAMPPRocky/tokei.git tokei"
-
 ##### Guix integration
 # [[ -s "$HOME/.guix-profile/etc/profile" ]] && source "$HOME/.guix-profile/etc/profile"
 
+wrap_prompt_command_initializer() {
+	local initializer_cmd="$1"
+	local initializer_code=""
+	local initializer_code_return_code=0
+	report_prompt_commands "before" "$initializer_cmd"
+	initializer_code=$(eval "$initializer_cmd")
+	initializer_code_return_code=$?
+	if [ -z "$initializer_code" ] && [ $initializer_code_return_code -eq 0 ]; then
+		# If the initializer code returned nothing and didn't error,
+		# then $initializer_cmd was actually meant to be run
+		# in the current context, instead of in a subshell generating the code to run
+		# (yes, this gets confusing...)
+		# Note that this is suboptimal since we are running it TWICE,
+		# but there's no other way to know without doing code analysis
+		eval "$initializer_cmd"
+		initializer_code_return_code=$?
+		truthy DEBUG_PROMPT_COMMANDS && echo "Ran '$initializer_cmd'"
+	elif ! [ -z "$initializer_code" ]; then
+		# if the initializer code generated MORE code, then run that code in
+		# the current context
+		eval "$initializer_code"
+		initializer_code_return_code=$?
+		truthy DEBUG_PROMPT_COMMANDS && echo "Ran the code generated by '$initializer_cmd'"
+	else
+		echo "Error: Initializer '$initializer_cmd' returned nothing and an error code of $initializer_code_return_code" >&2
+		return $initializer_code_return_code
+	fi
+	if [[ -n "$PROMPT_COMMAND" ]]; then
+		truthy DEBUG_PROMPT_COMMANDS && echo "Adding '$PROMPT_COMMAND' to PROMPT_ARRAY"
+		PROMPT_ARRAY+=("$PROMPT_COMMAND")
+		truthy DEBUG_PROMPT_COMMANDS && echo "PROMPT_ARRAY is now: ${PROMPT_ARRAY[@]}"
+	fi
+	report_prompt_commands "after" "$initializer_cmd"
+	return $initializer_code_return_code
+}
+
 # echo "before direnv hook: $(declare -p PROMPT_COMMAND)"
+# Wrapper function to preserve PROMPT_COMMAND when it's a Bash array
+# wrap_prompt_command_initializer_old() {
+#   local initializer_cmd="$1"
+#   report_prompt_commands "before" "$initializer_cmd"
+#   if ! [[ "$(declare -p precmd_functions 2>&1)" == "declare -a"* ]]; then
+#     precmd_functions=()
+#   fi
+
+#   # Check if PROMPT_COMMAND is a Bash array
+#   if [[ "$(declare -p PROMPT_COMMAND 2>&1)" == "declare -a"* ]]; then
+#     # Add the current PROMPT_COMMAND array to precmd_functions
+#     precmd_functions+=("${PROMPT_COMMAND[@]}")
+		
+#     # Set PROMPT_COMMAND to empty string
+#     # unset PROMPT_COMMAND # since the following line won't erase its array type (!)
+#     # PROMPT_COMMAND=""
+		
+#     # Run the initializer
+#     eval "$($initializer_cmd)"
+		
+#     # Check if PROMPT_COMMAND is still a string (not an array)
+#     if ! [[ "$(declare -p PROMPT_COMMAND 2>&1)" == "declare -a"* ]]; then
+#       # Get the string value and append it as array elements to a new PROMPT_COMMAND
+#       local prompt_cmd_string="$PROMPT_COMMAND"
+#       # unset PROMPT_COMMAND
+#       # declare -a PROMPT_COMMAND
+#       IFS=';' read -ra PROMPT_COMMAND <<< "$prompt_cmd_string"
+#     else
+#       echo "Error: Initializer '$initializer_cmd' unexpectedly set PROMPT_COMMAND as an array" >&2
+#       return 1
+#     fi
+#   elif [[ "$(declare -p PROMPT_COMMAND 2>&1)" == "declare --"* ]]; then
+#     # If PROMPT_COMMAND is not an array, but has a value, just run the initializer,
+#     # preserving old value in precmd_functions and setting PROMPT_COMMAND to a Bash array again
+#     if [ "${PROMPT_COMMAND}" != "" ]; then
+#       precmd_functions+=("${PROMPT_COMMAND[@]}")
+#       # unset PROMPT_COMMAND
+#       # PROMPT_COMMAND=""
+#       # Run the initializer
+#       eval "$($initializer_cmd)"
+#       # Check if PROMPT_COMMAND is still a string (not an array)
+#       if ! [[ "$(declare -p PROMPT_COMMAND 2>&1)" == "declare -a"* ]]; then
+#         # Get the string value and append it as array elements to a new PROMPT_COMMAND
+#         local prompt_cmd_string="$PROMPT_COMMAND"
+#         PROMPT_ARRAY+=("$prompt_cmd_string")
+#         # unset PROMPT_COMMAND
+#         # PROMPT_COMMAND=""
+#       else
+#         echo "Error: Initializer '$initializer_cmd' unexpectedly set PROMPT_COMMAND as an array" >&2
+#         return 1
+#       fi
+#     elif [ "${PROMPT_COMMAND}" == "" ]; then
+#       :
+#     else
+#       echo "Error: Initializer '$initializer_cmd' couldn't cope with PROMPT_COMMAND value of '${PROMPT_COMMAND}'" >&2
+#       return 1
+#     fi
+#   else
+#     echo "Error: Initializer '$initializer_cmd' skipped since PROMPT_COMMAND is set to something unexpected" >&2
+#     return 1
+#   fi
+
+#   report_prompt_commands "after" "$initializer_cmd"
+# }
+
+# The initializers are now centrally managed at the end of this file
+
 ##### direnv hook
-needs direnv
-if [ $? -eq 0 ]; then
-  # if array_contains_element precmd_functions _direnv_hook; then
-  #   :
-  # else
-    eval "$(direnv hook bash)" >/dev/null 2>&1
-  # fi
-fi
-
-# echo "after dirfuck:"
-# declare -p PROMPT_COMMAND; declare -p precmd_functions
-
-# line completion
-# nope, doesn't work right with starship
-# source ~/linecomp/linecomp.sh
-
-##### git completion functions and extra config
-# disabled for now due to age (2008) and suspicion that it's interfering with other hooks
-# source_relative_once bin/functions/git-branch.bash # defines parse_git_branch and parse_git_branch_with_dirty
-# source_relative_once bin/functions/git-completion.bash
+# needs direnv
+# if [ $? -eq 0 ]; then
+#   wrap_prompt_command_initializer "direnv hook bash"
+# fi
 
 # echo "before mcfly hook: $(declare -p PROMPT_COMMAND)"
 ##### mcfly integration (access via ctrl-r)
-needs mcfly "curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sudo sh -s -- --git cantino/mcfly"
-if [ $? -eq 0 ]; then
-  # if array_contains_element precmd_functions mcfly_prompt_command; then
-  #   :
-  # else
-    eval "$(mcfly init bash)"
-  # fi
-fi
+# needs mcfly "curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sudo sh -s -- --git cantino/mcfly"
+# if [ $? -eq 0 ]; then
+#   wrap_prompt_command_initializer "mcfly init bash"
+# fi
 
-# echo "after mcfuck:"
+# echo "after mcfuckery:"
 # declare -p PROMPT_COMMAND; declare -p precmd_functions
 
 # So at this point we want to handle this more intelligently; let's assert
@@ -99,6 +262,34 @@ fi
 # and unique them
 # uniquify_array precmd_functions
 
+# echo "before starship hook: $(declare -p PROMPT_COMMAND)"
+##### starship
+# it claims it will work with bash-preexec if it's loaded, so we run this after that hook
+# Actually, turns out it's full of shit and a dirty hack, so we actually run it first
+# to minimize its brain damage to PROMPT_COMMAND hooking; see below
+# needs starship
+# if [ $? -eq 0 ]; then
+#   wrap_prompt_command_initializer "starship init bash"
+# fi
+
+## SET UP CUSTOM HOOKS HERE
+# set up default terminal directory using OSC 7
+set_up_osc7_home() {
+	if array_contains_element precmd_functions __wezterm_osc7_home; then
+		:
+	else
+		precmd_functions+=(__wezterm_osc7_home)
+	fi
+}
+
+# DO_NOT() { :; }; ONLY() { :; };
+
+# DO_NOT ADD ANY MORE CUSTOM COMMANDLINE HOOKS/INITIALIZERS AFTER THIS POINT
+
+# ONLY BASH_PREEXEC CONFIG SHOULD BE BELOW THIS LINE
+
+# unset DO_NOT ONLY
+
 # echo "before bash-preexec hook: $(declare -p PROMPT_COMMAND)"
 ##### bash-preexec
 # You'll want to pull down the file and add it to your bash profile/configuration (i.e ~/.bashrc, ~/.profile, ~/.bash_profile, etc).
@@ -106,13 +297,34 @@ fi
 # Pull down our file from GitHub and write it to your home directory as a hidden file.
 export BASH_PREEXEC_LOCATION="$HOME/dotfiles/lib/bash-preexec.sh"
 update_bash_preexec() {
-  [ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
-  mkdir -p ~/dotfiles/lib
-  curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o "$BASH_PREEXEC_LOCATION"
+	[ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
+	mkdir -p ~/dotfiles/lib
+	curl https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh -o "$BASH_PREEXEC_LOCATION"
 }
-# Source this file at the end of your bash profile (e.g. ~/.bashrc, ~/.profile, or ~/.bash_profile)
-[[ -f "$BASH_PREEXEC_LOCATION" ]] && source "$BASH_PREEXEC_LOCATION" || \
-  echo -e "Problem when setting up bash_preexec config from ${BASH_PREEXEC_LOCATION}; it is nonexistent.\n You may need to run update_bash_preexec to fix this."
+# Run all initializers in the correct order
+# First, run tools that modify PROMPT_COMMAND directly
+command -v zoxide >/dev/null 2>&1 && wrap_prompt_command_initializer "zoxide init --cmd cd --hook pwd bash" || err "zoxide not found"
+command -v direnv >/dev/null 2>&1 && wrap_prompt_command_initializer "direnv hook bash" || err "direnv not found"
+command -v mcfly >/dev/null 2>&1 && wrap_prompt_command_initializer "mcfly init bash" || err "mcfly not found"
+
+# Then run starship which uses precmd_functions
+command -v starship >/dev/null 2>&1 && wrap_prompt_command_initializer "starship init bash" || err "starship not found"
+
+# Run any custom hooks
+wrap_prompt_command_initializer "set_up_osc7_home"
+
+# Source bash-preexec LAST to ensure it can see all hooks
+if [ -f "$BASH_PREEXEC_LOCATION" ]; then
+	# Source bash-preexec directly to ensure it works properly
+	source "$BASH_PREEXEC_LOCATION" || \
+		echo -e "Problem when setting up bash_preexec config from ${BASH_PREEXEC_LOCATION}; it errored.\n You may need to run update_bash_preexec to fix this."
+	# Ensure precmd_functions are properly registered
+	if [[ "$(declare -p precmd_functions 2>&1)" == "declare -a"* ]] && [[ "${#precmd_functions[@]}" -gt 0 ]]; then
+		truthy DEBUG_PROMPT_COMMANDS && echo "Registered ${#precmd_functions[@]} precmd functions with bash-preexec"
+	fi
+else
+	echo -e "Problem when setting up bash_preexec config from ${BASH_PREEXEC_LOCATION}; it is nonexistent.\n You may need to run update_bash_preexec to fix this."
+fi
 
 # and then force PROMPT_COMMAND to just be the bash_preexec hook
 # PROMPT_COMMAND=([0]="__bp_precmd_invoke_cmd" [1]="__bp_interactive_mode")
@@ -123,33 +335,6 @@ update_bash_preexec() {
 # else
 #   precmd_functions+=(precmd)
 # fi
-
-# echo "before starship hook: $(declare -p PROMPT_COMMAND)"
-##### starship
-# it claims it will work with bash-preexec if it's loaded, so we run this after that hook
-# Actually, turns out it's full of shit and a dirty hack, so we actually run it first
-# to minimize its brain damage to PROMPT_COMMAND hooking; see below
-needs starship
-if [ $? -eq 0 ]; then
-  # if array_contains_element precmd_functions starship_precmd; then
-  #   :
-  # else
-# starship init bash
-    eval "$(starship init bash)"
-  # fi
-fi
-
-# echo "after starshit:"
-# declare -p PROMPT_COMMAND; declare -p precmd_functions
-
-## SET UP CUSTOM HOOKS HERE
-[ "`type -t array_contains_element`" = "function" ] || . "${HOME}/dotfiles/bin/functions/utility_functions.bash"
-# set up default terminal directory using OSC 7
-if array_contains_element precmd_functions __wezterm_osc7_home; then
-  :
-else
-  precmd_functions+=(__wezterm_osc7_home)
-fi
 
 # _writehist() {
 #   # echo "writing history..."
diff --git a/bin/bashorg_quote b/bin/bashorg_quote
--- a/bin/bashorg_quote
+++ b/bin/bashorg_quote
@@ -1,60 +1,46 @@
-#!/usr/bin/env moonrun
--- math.randomseed os.time! -- this was too low-rez, so:
+#!/usr/bin/env bash
 
-ffi = require "ffi"
-ffi.cdef [[
-	typedef long time_t;
-	typedef struct timeval {
-		time_t tv_sec;
-		time_t tv_usec;
-	} timeval;
-	int gettimeofday(struct timeval* tv, void* tz);
-]]
-seed = ->
-	tv = ffi.new "timeval"
-	ffi.C.gettimeofday tv, nil
-	sec = tonumber tv.tv_sec
-	usec = tonumber tv.tv_usec
-	math.randomseed sec * 1e6 + usec
-	math.random!
-
-seed!
-
-get_script_dir = ->
-	src = debug.getinfo(2, "S").source
-	if src\match "^@"
-		return src\match("^@(.-)[^/]+$") -- extract path prefix
-	else
-		return "./"
-
-parse_quotes = (filename) ->
-	quotes = {}
-	total_score = 0
-
-	for line in io.lines filename
-		id, score, quote = line\match("^(%d+)\t(%d+)\t(.+)$")
-		continue unless id and score and quote
-
-		score = tonumber score
-		total_score += score + 10
-		table.insert quotes, {
-			score: score + 10
-			quote: quote
-			cumulative: total_score
+bashorg_quote() {
+	[ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
+	# Extract quote data from bashorg_quotes.tsv in the same directory as this script
+	local script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
+	local quotes_file="$script_dir/src/bashorg_quotes_unwrapped.tsv"
+	if [[ ! -f "$quotes_file" ]]; then
+		echo "Error: quotes file '$quotes_file' not found." >&2
+		return 1
+	fi
+	local AWK=${AWK:-$(choose_awk)}
+	# Use awk to process the data, sort by score, and select a random quote
+	$AWK -F'\t' '
+		BEGIN { srand() }
+		{
+			score = $2 + 10;
+			quotes[NR] = $0;
+			total += score;
+			scores[NR] = total;
 		}
+		END {
+			random_num = int(rand() * total);
+			for (i = 1; i <= NR; i++) {
+				if (scores[i] >= random_num) {
+					split(quotes[i], fields, "\t");
+					gsub(/\\n/, "\n", fields[3]);
+					print fields[3];
+					exit;
+				}
+			}
+		}
+	' "$quotes_file"
+}
 
-	quotes, total_score
-
-pick_quote = (quotes, total_score) ->
-	r = math.random total_score
-	for q in *quotes
-		if q.cumulative >= r
-			return q.quote\gsub("\\n", "\n")
-
-main = ->
-	script_dir = get_script_dir!
-	quotes_file = script_dir .. "functions/bashorg_quotes_unwrapped.tsv"
-	quotes, total = parse_quotes quotes_file
-	print (pick_quote quotes, total)
-
-main!
+# Run the function if this script is executed directly
+if ! (return 0 2>/dev/null); then
+	# Check if we are running tests
+	if [ "$1" = "--test" ]; then
+		# Run tests from the test file
+		. "$HOME/dotfiles/bin/test/$(basename "${0##\-}")_test"
+	else
+		# If called directly, pass all arguments to the function
+		$(basename "${0##\-}") "$@"
+	fi
+fi
diff --git a/bin/goodnight_message b/bin/goodnight_message
--- a/bin/goodnight_message
+++ b/bin/goodnight_message
@@ -9,8 +9,8 @@ MESSAGES_DIR="$HOME/goodnight_messages"
 LOG_FILE="$MESSAGES_DIR/goodnight_script.log"
 # Error if the env hasn't provided ANTHROPIC_API_KEY or ELEVENLABS_API_KEY
 if [ -z "$ANTHROPIC_API_KEY" ] || [ -z "$ELEVENLABS_API_KEY" ]; then
-    echo "Error: ANTHROPIC_API_KEY or ELEVENLABS_API_KEY is not set"
-    exit 1
+	echo "Error: ANTHROPIC_API_KEY or ELEVENLABS_API_KEY is not set"
+	exit 1
 fi
 # NOTE: Please check https://docs.anthropic.com for the latest API version
 # and update the 'anthropic-version' header below if necessary.
@@ -29,88 +29,88 @@ mkdir -p "$MESSAGES_DIR"
 
 # Logging function
 log() {
-    echo "$(date): $1" >> "$LOG_FILE"
+	echo "$(date): $1" >> "$LOG_FILE"
 }
 
 # Function to generate message using Anthropic API
 generate_message() {
-    local prompt="I need a nudge to go to sleep at 11pm. A lack of sleep impairs self-regulation and self-control, which can produce more negativity. Research has linked poor sleep to frustration, impatience, hostility, anxiety, low levels of joviality, lower levels of trust, workplace deviance, and unethical behavior. Sleep deprivation also hurts the relationship between leaders and their followers, and diminishes how much help people provide to others. So write me an encouraging but urgent reminder to head to bed, tailored to me, that perhaps mentions the advantages of sleep, and teasingly jokes me about saving the game or putting down the tech project in whatever functional language I am working on. I will be voicing what you say using the Raphael voice from Baldurs Gate 3 (Andrew Wincott) so make sure to say something in his fancy-yet-doom-and-gloom conversational style. Do not acknowledge this request, do not incluce stage direction or action lines, provide only the dialogue as Raphael would speak it, because this output will be sent directly to a voice generator."
-    log "Sending request to OpenAI API with prompt:\n$prompt"
+	local prompt="I need a nudge to go to sleep at 11pm. A lack of sleep impairs self-regulation and self-control, which can produce more negativity. Research has linked poor sleep to frustration, impatience, hostility, anxiety, low levels of joviality, lower levels of trust, workplace deviance, and unethical behavior. Sleep deprivation also hurts the relationship between leaders and their followers, and diminishes how much help people provide to others. So write me an encouraging but urgent reminder to head to bed, tailored to me, that perhaps mentions the advantages of sleep, and teasingly jokes me about saving the game or putting down the tech project in whatever functional language I am working on. I will be voicing what you say using the Raphael voice from Baldurs Gate 3 (Andrew Wincott) so make sure to say something in his fancy-yet-doom-and-gloom conversational style. Do not acknowledge this request, do not incluce stage direction or action lines, provide only the dialogue as Raphael would speak it, because this output will be sent directly to a voice generator."
+	log "Sending request to OpenAI API with prompt:\n$prompt"
 
-    local response=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
-        -H "Content-Type: application/json" \
-        -H "Authorization: Bearer $OPENAI_API_KEY" \
-        -d '{
-            "model": "'"$OPENAI_MODEL"'",
-            "messages": [{"role": "user", "content": "'"$prompt"'"}],
-            "max_tokens": 300
-        }')
+	local response=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
+		-H "Content-Type: application/json" \
+		-H "Authorization: Bearer $OPENAI_API_KEY" \
+		-d '{
+			"model": "'"$OPENAI_MODEL"'",
+			"messages": [{"role": "user", "content": "'"$prompt"'"}],
+			"max_tokens": 300
+		}')
 
-    log "Received response from OpenAI API: $response"
+	log "Received response from OpenAI API: $response"
 
-    if [ -z "$response" ]; then
-        log "Error: Empty response from OpenAI API"
-        return 1
-    fi
+	if [ -z "$response" ]; then
+		log "Error: Empty response from OpenAI API"
+		return 1
+	fi
 
-    local message=$(echo "$response" | jq -r '.choices[0].message.content')
-    if [ "$message" = "null" ] || [ -z "$message" ]; then
-        log "Error: Failed to extract message from OpenAI API response"
-        return 1
-    fi
+	local message=$(echo "$response" | jq -r '.choices[0].message.content')
+	if [ "$message" = "null" ] || [ -z "$message" ]; then
+		log "Error: Failed to extract message from OpenAI API response"
+		return 1
+	fi
 
-    # Remove newlines and escape special characters
-    message=$(echo "$message" | tr '\n' ' ' | $SED 's/"/\\"/g' | $SED "s/'/\\'/g")
+	# Remove newlines and escape special characters
+	message=$(echo "$message" | tr '\n' ' ' | $SED 's/"/\\"/g' | $SED "s/'/\\'/g")
 
-    echo "$message"
+	echo "$message"
 }
 
 # Function to generate audio using ElevenLabs API
 generate_audio() {
-    local text="$1"
-    log "Sending request to ElevenLabs API"
-    local response=$(curl -s -X POST "https://api.elevenlabs.io/v1/text-to-speech/$ELEVENLABS_VOICE_ID" \
-        -H "Content-Type: application/json" \
-        -H "xi-api-key: $ELEVENLABS_API_KEY" \
-        -d "{
-              \"text\": \"$text\",
-              \"model_id\": \"eleven_multilingual_v2\",
-              \"voice_settings\": {
-                  \"stability\": $STABILITY,
-                  \"similarity_boost\": $SIMILARITY_BOOST,
-                  \"style\": $STYLE,
-                  \"use_speaker_boost\": $SPEAKER_BOOST
-              }
-            }" \
-        --output "$MESSAGES_DIR/goodnight_message.mp3")
-    # if the file type of the response is not audio/mpeg, then log the response and exit with error
-    if [ "$(file -b --mime-type "$MESSAGES_DIR/goodnight_message.mp3")" != "audio/mpeg" ]; then
-        log "Error: Failed to generate audio file. Response:\n$(cat $MESSAGES_DIR/goodnight_message.mp3)"
-        return 1
-    else
-        log "Successfully generated audio file"
-    fi
+	local text="$1"
+	log "Sending request to ElevenLabs API"
+	local response=$(curl -s -X POST "https://api.elevenlabs.io/v1/text-to-speech/$ELEVENLABS_VOICE_ID" \
+		-H "Content-Type: application/json" \
+		-H "xi-api-key: $ELEVENLABS_API_KEY" \
+		-d "{
+			  \"text\": \"$text\",
+			  \"model_id\": \"eleven_multilingual_v2\",
+			  \"voice_settings\": {
+				  \"stability\": $STABILITY,
+				  \"similarity_boost\": $SIMILARITY_BOOST,
+				  \"style\": $STYLE,
+				  \"use_speaker_boost\": $SPEAKER_BOOST
+			  }
+			}" \
+		--output "$MESSAGES_DIR/goodnight_message.mp3")
+	# if the file type of the response is not audio/mpeg, then log the response and exit with error
+	if [ "$(file -b --mime-type "$MESSAGES_DIR/goodnight_message.mp3")" != "audio/mpeg" ]; then
+		log "Error: Failed to generate audio file. Response:\n$(cat $MESSAGES_DIR/goodnight_message.mp3)"
+		return 1
+	else
+		log "Successfully generated audio file"
+	fi
 }
 
 # Function to play audio and send notification
 play_audio_and_notify() {
-    local message="$1"
+	local message="$1"
 
-    # Play audio
-    if [[ "$OSTYPE" == "darwin"* ]]; then
-        afplay "$MESSAGES_DIR/goodnight_message.mp3"
-    else
-        mpg123 "$MESSAGES_DIR/goodnight_message.mp3"
-    fi
+	# Play audio
+	if [[ "$OSTYPE" == "darwin"* ]]; then
+		afplay "$MESSAGES_DIR/goodnight_message.mp3"
+	else
+		mpg123 "$MESSAGES_DIR/goodnight_message.mp3"
+	fi
 
-    # Send notification
-    if [[ "$OSTYPE" == "darwin"* ]]; then
-        osascript -e "display notification \"$message\" with title \"Goodnight Message\""
-    else
-        notify-send "Goodnight Message" "$message"
-    fi
+	# Send notification
+	if [[ "$OSTYPE" == "darwin"* ]]; then
+		osascript -e "display notification \"$message\" with title \"Goodnight Message\""
+	else
+		notify-send "Goodnight Message" "$message"
+	fi
 
-    log "Played audio and sent notification"
+	log "Played audio and sent notification"
 }
 
 # Main script
@@ -118,8 +118,8 @@ log "Script started"
 
 message=$(generate_message)
 if [ $? -ne 0 ]; then
-    log "Failed to generate message. Exiting."
-    exit 1
+	log "Failed to generate message. Exiting."
+	exit 1
 fi
 
 echo "Generated message: $message"
@@ -127,14 +127,14 @@ log "Generated message: $message"
 
 # Move existing file if it exists
 if [ -f "$MESSAGES_DIR/goodnight_message.mp3" ]; then
-    mv "$MESSAGES_DIR/goodnight_message.mp3" "$MESSAGES_DIR/goodnight_message_$(date -r "$MESSAGES_DIR/goodnight_message.mp3" +%Y%m%d).mp3"
-    log "Moved existing audio file"
+	mv "$MESSAGES_DIR/goodnight_message.mp3" "$MESSAGES_DIR/goodnight_message_$(date -r "$MESSAGES_DIR/goodnight_message.mp3" +%Y%m%d).mp3"
+	log "Moved existing audio file"
 fi
 
 generate_audio "$message"
 if [ $? -ne 0 ]; then
-    log "Failed to generate audio. Exiting."
-    exit 1
+	log "Failed to generate audio. Exiting."
+	exit 1
 fi
 
 play_audio_and_notify "$message"
diff --git a/bin/imagine b/bin/imagine
--- a/bin/imagine
+++ b/bin/imagine
@@ -1,50 +1,36 @@
 #!/usr/bin/env bash
 
-# graceful dependency enforcement
-# Usage: needs <executable> [provided by <packagename>]
-# only redefines it here if it's not already defined
->/dev/null declare -F needs || \
-needs() {
-  [ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
-  local bin=$1
-  shift
-  command -v "$bin" >/dev/null 2>&1 || { echo >&2 "I require $bin but it's not installed or in PATH; $*"; return 1; }
-}
-
-. "$HOME/dotfiles/bin/functions/source_relative.bash"
-source_relative_once $HOME/dotfiles/bin/datetimestamp
 # Uses the OpenAI image generation API to generate an image from a prompt
 # and output it to the terminal via the sixel protocol.
 # Example usage: imagine a cow jumping over the moon
 imagine() {
-  [ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
-  needs magick Please install ImageCraptastick I mean ImageMagick
-  local prompt geometry create_img url rand_num stamp filename response maybe_error
-  prompt="$@"
-  geometry=${GEOMETRY:-512x512} # options: 256x256, 512x512, or 1024x1024
-  create_img=$(curl https://api.openai.com/v1/images/generations -s \
-    -H "Content-Type: application/json" \
-    -H "Authorization: Bearer $OPENAI_API_KEY" \
-    -d "{\"prompt\": \"$prompt\", \"n\": 1, \"size\": \"$geometry\"}"
-  )
-  if echo "$create_img" | jq -e '.error' >/dev/null; then
-    echo -n "Error: " >&2
-    echo "$create_img" | jq -r '.error.message' >&2
-    return 1
-  fi
-  (( DEBUG )) && echo $create_img | jq >&2
-  url=$(echo $create_img | jq -r '.data[0].url')
-  # rand_num=$(shuf -i 1-1000000 -n 1)
-  stamp=$(DATETIMESTAMPFORMAT="+%Y%m%d%H%M%S%N" datetimestamp)
-  filename=$(gmktemp -t "img-${stamp}-XXXX" --suffix .png)
-  response=$(curl -s $url -o "$filename")
-  (( DEBUG )) && echo "debug: $response" >&2
-  magick "$filename" -geometry $geometry sixel:-
-  echo "This image is currently stored temporarily at: $filename" >&2
+	[ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
+	needs magick Please install ImageCraptastick I mean ImageMagick
+	local prompt geometry create_img url rand_num stamp filename response maybe_error
+	prompt="$@"
+	geometry=${GEOMETRY:-512x512} # options: 256x256, 512x512, or 1024x1024
+	create_img=$(curl https://api.openai.com/v1/images/generations -s \
+		-H "Content-Type: application/json" \
+		-H "Authorization: Bearer $OPENAI_API_KEY" \
+		-d "{\"prompt\": \"$prompt\", \"n\": 1, \"size\": \"$geometry\"}"
+	)
+	if echo "$create_img" | jq -e '.error' >/dev/null; then
+		echo -n "Error: " >&2
+		echo "$create_img" | jq -r '.error.message' >&2
+		return 1
+	fi
+	(( DEBUG )) && echo $create_img | jq >&2
+	url=$(echo $create_img | jq -r '.data[0].url')
+	# rand_num=$(shuf -i 1-1000000 -n 1)
+	stamp=$(DATETIMESTAMPFORMAT="+%Y%m%d%H%M%S%N" datetimestamp)
+	filename=$(gmktemp -t "img-${stamp}-XXXX" --suffix .png)
+	response=$(curl -s $url -o "$filename")
+	(( DEBUG )) && echo "debug: $response" >&2
+	magick "$filename" -geometry $geometry sixel:-
+	echo "This image is currently stored temporarily at: $filename" >&2
 }
 
 # Export the function so it can be used by find -exec
-export -f imagine
 
 # Run the function, passing along any args, if this file was run directly (such as via sudo) instead of as an include
 # Sometimes, $0 contains a leading dash to indicate an interactive (or is it login?) shell,
@@ -54,3 +40,14 @@ if [ "$_me" = "imagine" ]; then
 	$_me "$@"
 fi
 unset _me
+# Run the function if this script is executed directly
+if ! (return 0 2>/dev/null); then
+	# Check if we are running tests
+	if [ "$1" = "--test" ]; then
+		# Run tests from the test file
+		. "$HOME/dotfiles/bin/test/$(basename "${0##\-}")_test"
+	else
+		# If called directly, pass all arguments to the function
+		$(basename "${0##\-}") "$@"
+	fi
+fi
diff --git a/bin/install-proton-game-mod b/bin/install-proton-game-mod
--- a/bin/install-proton-game-mod
+++ b/bin/install-proton-game-mod
@@ -7,34 +7,34 @@ TXTRST=${TXTRST:-"m"}
 
 >/dev/null declare -F warn || \
 warn() {
-  echo -e "${ANSI}${TXTYLW}$1${ANSI}${TXTRST}" 1>&2
+	echo -e "${ANSI}${TXTYLW}$1${ANSI}${TXTRST}" 1>&2
 }
 
 >/dev/null declare -F err || \
 err() {
-  echo -e "${ANSI}${TXTRED}$1${ANSI}${TXTRST}" 1>&2
+	echo -e "${ANSI}${TXTRED}$1${ANSI}${TXTRST}" 1>&2
 }
 
 needs() {
-  local bin=$1;
-  shift;
-  command -v $bin > /dev/null 2>&1 || {
-    echo "I require $bin but it's not installed or in PATH; $*" 1>&2;
-    return 1
-  }
+	local bin=$1;
+	shift;
+	command -v $bin > /dev/null 2>&1 || {
+		echo "I require $bin but it's not installed or in PATH; $*" 1>&2;
+		return 1
+	}
 }
 
 fix_nvse_capitalization_via_symlinking() {
-  if [ -d "$1/NVSE" ] && [ -d "$1/nvse" ] && [ ! -h "$1/NVSE" ]; then
-    warn "Fixing NVSE capitalization via symlinking..."
-    pushd "$1" > /dev/null
-      pushd NVSE > /dev/null
-        cp -r * ../nvse
-      popd > /dev/null
-      rm -rf NVSE
-      ln -s nvse NVSE
-    popd > /dev/null
-  fi
+	if [ -d "$1/NVSE" ] && [ -d "$1/nvse" ] && [ ! -h "$1/NVSE" ]; then
+		warn "Fixing NVSE capitalization via symlinking..."
+		pushd "$1" > /dev/null
+			pushd NVSE > /dev/null
+				cp -r * ../nvse
+			popd > /dev/null
+			rm -rf NVSE
+			ln -s nvse NVSE
+		popd > /dev/null
+	fi
 }
 
 fdbin=fd
@@ -45,46 +45,46 @@ needs fzy https://github.com/jhawthorn/fzy
 needs 7z
 needs unrar
 case "$1" in
-  "fnv")
-    APP_NAME=FalloutNV.exe
-    echo "Which ${APP_NAME}?"
-    APP_DIR="$(dirname "$(realpath "$($fdbin -HI -t f -e exe $APP_NAME $HOME | fzy)")")"
-    warn "Found $APP_NAME in '$APP_DIR'"
-    echo "Which mod in the Downloads folder?"
-    MOD_FILE="$(realpath "$($fdbin -t f -e 7z -e zip -e rar -d 1 . ~/Downloads | fzy)")"
-    warn "Found '$MOD_FILE'"
-    # switch based on the file extension
-    case "${MOD_FILE##*.}" in
-      7z | zip)
-        install_command="7z x -y \"$MOD_FILE\" -o"
-        install_to_root_dir="$(7z l -slt "$MOD_FILE" | grep -m 1 "Path = Data\b")"
-        ;;
-      rar)
-        install_command="unrar x \"$MOD_FILE\" "
-        # warn "unrar lt \"$MOD_FILE\" | grep -z -o -E -m 1 \"Name: Data[[:space:]]+Type: Directory\""
-        # grep with -z outputs an ending null byte, which makes command substitution error, so we tr it out
-        install_to_root_dir="$(unrar lt "$MOD_FILE" | grep -z -E -m 1 "Name: Data[[:space:]]+Type: Directory" | tr -d '\0')"
-        ;;
-      *)
-        err "Unknown file extension: ${MOD_FILE##*.}"
-        exit 1
-        ;;
-    esac
-    # if archive root contains a "Data" folder, install to root game folder
-    if [ -n "$install_to_root_dir" ]; then
-      INSTALL_DIR="$APP_DIR"
-    else
-      INSTALL_DIR="$APP_DIR/Data"
-    fi
-    warn "Installing to '$INSTALL_DIR'..."
-    warn "${install_command}\"${INSTALL_DIR}\""
-    # set -x
-    eval "$install_command\"$INSTALL_DIR\""
-    # set +x
-    fix_nvse_capitalization_via_symlinking "$APP_DIR/Data"
-    ;;
-  *)
-    echo "Game shortcut not recognized. Options: fnv"
-    exit 1
-    ;;
+	"fnv")
+		APP_NAME=FalloutNV.exe
+		echo "Which ${APP_NAME}?"
+		APP_DIR="$(dirname "$(realpath "$($fdbin -HI -t f -e exe $APP_NAME $HOME | fzy)")")"
+		warn "Found $APP_NAME in '$APP_DIR'"
+		echo "Which mod in the Downloads folder?"
+		MOD_FILE="$(realpath "$($fdbin -t f -e 7z -e zip -e rar -d 1 . ~/Downloads | fzy)")"
+		warn "Found '$MOD_FILE'"
+		# switch based on the file extension
+		case "${MOD_FILE##*.}" in
+			7z | zip)
+				install_command="7z x -y \"$MOD_FILE\" -o"
+				install_to_root_dir="$(7z l -slt "$MOD_FILE" | grep -m 1 "Path = Data\b")"
+				;;
+			rar)
+				install_command="unrar x \"$MOD_FILE\" "
+				# warn "unrar lt \"$MOD_FILE\" | grep -z -o -E -m 1 \"Name: Data[[:space:]]+Type: Directory\""
+				# grep with -z outputs an ending null byte, which makes command substitution error, so we tr it out
+				install_to_root_dir="$(unrar lt "$MOD_FILE" | grep -z -E -m 1 "Name: Data[[:space:]]+Type: Directory" | tr -d '\0')"
+				;;
+			*)
+				err "Unknown file extension: ${MOD_FILE##*.}"
+				exit 1
+				;;
+		esac
+		# if archive root contains a "Data" folder, install to root game folder
+		if [ -n "$install_to_root_dir" ]; then
+			INSTALL_DIR="$APP_DIR"
+		else
+			INSTALL_DIR="$APP_DIR/Data"
+		fi
+		warn "Installing to '$INSTALL_DIR'..."
+		warn "${install_command}\"${INSTALL_DIR}\""
+		# set -x
+		eval "$install_command\"$INSTALL_DIR\""
+		# set +x
+		fix_nvse_capitalization_via_symlinking "$APP_DIR/Data"
+		;;
+	*)
+		echo "Game shortcut not recognized. Options: fnv"
+		exit 1
+		;;
 esac
diff --git a/bin/lsix b/bin/lsix
--- a/bin/lsix
+++ b/bin/lsix
@@ -39,164 +39,164 @@ fontsize=$((tilewidth/20))
 
 # Sanity check and compatibility
 if [[ ${BASH_VERSINFO[0]} -gt 3 ]]; then
-    timeout=0.25		# How long to wait for terminal to respond.
+	timeout=0.25		# How long to wait for terminal to respond.
 else
-    timeout=1			# Bash 3's `read` could not handle decimals.
+	timeout=1			# Bash 3's `read` could not handle decimals.
 fi
 
 if ! command -v montage >/dev/null; then
-    echo "Please install ImageMagick" >&2
-    exit 1
+	echo "Please install ImageMagick" >&2
+	exit 1
 fi
 
 cleanup() {
-    echo -n $'\e\\'		# Escape sequence to stop SIXEL.
-    stty echo			# Reset terminal to show characters.
-    exit 0
+	echo -n $'\e\\'		# Escape sequence to stop SIXEL.
+	stty echo			# Reset terminal to show characters.
+	exit 0
 }
 trap cleanup SIGINT SIGHUP SIGABRT EXIT
 
 autodetect() {
-    # Various terminal automatic configuration routines.
+	# Various terminal automatic configuration routines.
 
-    # Don't show escape sequences the terminal doesn't understand.
-    stty -echo			# Hush-a Mandara Ni Pari
+	# Don't show escape sequences the terminal doesn't understand.
+	stty -echo			# Hush-a Mandara Ni Pari
 
-    # TERMINAL COLOR AUTODETECTION.
-    # Find out how many color registers the terminal has
-    IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;1;0S' >&2
-    [[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
+	# TERMINAL COLOR AUTODETECTION.
+	# Find out how many color registers the terminal has
+	IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;1;0S' >&2
+	[[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
 
-    # BUG WORKAROUND: mlterm does not report number of colors.
-    if [[ $TERM =~ mlterm ]]; then numcolors=1024; fi
+	# BUG WORKAROUND: mlterm does not report number of colors.
+	if [[ $TERM =~ mlterm ]]; then numcolors=1024; fi
 
-    # Increase colors, if needed
-    if [[ $numcolors -lt 256 ]]; then
-    # Attempt to set the number of colors to 256.
-    # This will work for xterm, but fail on a real vt340.
-    IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;3;256S' >&2
-    [[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
-    fi
+	# Increase colors, if needed
+	if [[ $numcolors -lt 256 ]]; then
+	# Attempt to set the number of colors to 256.
+	# This will work for xterm, but fail on a real vt340.
+	IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;3;256S' >&2
+	[[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
+	fi
 
-    # Query the terminal background and foreground colors.
-    IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]11;?\e\\' >&2
-    if [[ ${REPLY[1]} =~ ^rgb ]]; then
-    # Return value format: $'\e]11;rgb:ffff/0000/ffff\e\\'.
-    # ImageMagick wants colors formatted as #ffff0000ffff.
-    background='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
-    IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]10;?\e\\' >&2
-    if [[ ${REPLY[1]} =~ ^rgb ]]; then
-        foreground='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
-        # Check for "Reverse Video".
-        IFS=";?$"  read -a REPLY -s -t ${timeout} -d "y" -p $'\e[?5$p'
-        if [[ ${REPLY[2]} == 1 || ${REPLY[2]} == 3 ]]; then
-        temp=$foreground
-        foreground=$background
-        background=$temp
-        fi
-    fi
-    fi
+	# Query the terminal background and foreground colors.
+	IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]11;?\e\\' >&2
+	if [[ ${REPLY[1]} =~ ^rgb ]]; then
+	# Return value format: $'\e]11;rgb:ffff/0000/ffff\e\\'.
+	# ImageMagick wants colors formatted as #ffff0000ffff.
+	background='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+	IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]10;?\e\\' >&2
+	if [[ ${REPLY[1]} =~ ^rgb ]]; then
+		foreground='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+		# Check for "Reverse Video".
+		IFS=";?$"  read -a REPLY -s -t ${timeout} -d "y" -p $'\e[?5$p'
+		if [[ ${REPLY[2]} == 1 || ${REPLY[2]} == 3 ]]; then
+		temp=$foreground
+		foreground=$background
+		background=$temp
+		fi
+	fi
+	fi
 
-    # Try dtterm WindowOps to find out the window size.
-    IFS=";" read -a REPLY -s -t ${timeout} -d "t" -p $'\e[14t' >&2
-    if [[ $? == 0  &&  ${REPLY[2]} -gt 0 ]]; then
-    width=${REPLY[2]}
-    fi
+	# Try dtterm WindowOps to find out the window size.
+	IFS=";" read -a REPLY -s -t ${timeout} -d "t" -p $'\e[14t' >&2
+	if [[ $? == 0  &&  ${REPLY[2]} -gt 0 ]]; then
+	width=${REPLY[2]}
+	fi
 
-    # BUG WORKAROUND: XTerm cannot show images wider than 1000px.
-    # Remove this hack once XTerm gets fixed. Last checked: XTerm(327)
-    if [[ $TERM =~ xterm && $tilesize -ge 1000 ]]; then tilesize=1000; fi
+	# BUG WORKAROUND: XTerm cannot show images wider than 1000px.
+	# Remove this hack once XTerm gets fixed. Last checked: XTerm(327)
+	if [[ $TERM =~ xterm && $tilesize -ge 1000 ]]; then tilesize=1000; fi
 
-    [ -n "$DEBUG" ] && echo "width=$width"
-    # Space on either side of each tile is less than 0.5% of total screen width
-    tilexspace=$((width/201))
-    [ -n "$DEBUG" ] && echo "tilexspace=$tilexspace"
-    tileyspace=$((tilexspace/2 + 10))
-    [ -n "$DEBUG" ] && echo "tileyspace=$tileyspace"
-    # Figure out how many tiles we can fit per row. ("+ 1" is for -shadow).
-    numtiles=$((width/(tilewidth + 2*tilexspace + 1)))
-    [ -n "$DEBUG" ] && echo "numtiles=$numtiles"
+	[ -n "$DEBUG" ] && echo "width=$width"
+	# Space on either side of each tile is less than 0.5% of total screen width
+	tilexspace=$((width/201))
+	[ -n "$DEBUG" ] && echo "tilexspace=$tilexspace"
+	tileyspace=$((tilexspace/2 + 10))
+	[ -n "$DEBUG" ] && echo "tileyspace=$tileyspace"
+	# Figure out how many tiles we can fit per row. ("+ 1" is for -shadow).
+	numtiles=$((width/(tilewidth + 2*tilexspace + 1)))
+	[ -n "$DEBUG" ] && echo "numtiles=$numtiles"
 }
 
 main() {
-    # Discover and setup the terminal
-    autodetect
+	# Discover and setup the terminal
+	autodetect
 
-    if [[ $# == 0 ]]; then
-        # No command line args? Use a sorted list of image files in CWD.
-        shopt -s nullglob nocaseglob nocasematch
-        set - *{jpg,jpeg,png,gif,tiff,tif,p?m,x[pb]m,bmp,ico,svg,eps}
-        [[ $# != 0 ]] || exit
-        
-        # Read sorted filenames into array
-        declare -a files
-        while IFS= read -r line; do
-            files+=("$line")
-        done < <(printf "%s\n" "$@" | sort)
+	if [[ $# == 0 ]]; then
+		# No command line args? Use a sorted list of image files in CWD.
+		shopt -s nullglob nocaseglob nocasematch
+		set - *{jpg,jpeg,png,gif,tiff,tif,p?m,x[pb]m,bmp,ico,svg,eps}
+		[[ $# != 0 ]] || exit
+		
+		# Read sorted filenames into array
+		declare -a files
+		while IFS= read -r line; do
+			files+=("$line")
+		done < <(printf "%s\n" "$@" | sort)
 
-        # Only show first frame of animated GIFs if filename not specified.
-        for x in ${!files[@]}; do
-            if [[ ${files[$x]} =~ gif$ ]]; then
-                files[$x]+="[0]"
-            fi
-        done
-        set - "${files[@]}"
-    fi
+		# Only show first frame of animated GIFs if filename not specified.
+		for x in ${!files[@]}; do
+			if [[ ${files[$x]} =~ gif$ ]]; then
+				files[$x]+="[0]"
+			fi
+		done
+		set - "${files[@]}"
+	fi
 
-    # Resize on load: Save memory by appending this suffix to every filename.
-    resize="[${tilewidth}x${tileheight}]"
+	# Resize on load: Save memory by appending this suffix to every filename.
+	resize="[${tilewidth}x${tileheight}]"
 
 
-    imoptions="-tile ${numtiles}x1" # Each montage is 1 row x $numtiles columns
-    imoptions+=" -geometry ${tilewidth}x${tileheight}>+${tilexspace}+${tileyspace}" # Size of each tile and spacing
-    imoptions+=" -background $background -fill $foreground" # Use terminal's colors
-    imoptions+=" -auto-orient "	# Properly rotate JPEGs from cameras
-    if [[ $numcolors -gt 16 ]]; then
-    imoptions+=" -shadow "		# Just for fun :-)
-    fi
+	imoptions="-tile ${numtiles}x1" # Each montage is 1 row x $numtiles columns
+	imoptions+=" -geometry ${tilewidth}x${tileheight}>+${tilexspace}+${tileyspace}" # Size of each tile and spacing
+	imoptions+=" -background $background -fill $foreground" # Use terminal's colors
+	imoptions+=" -auto-orient "	# Properly rotate JPEGs from cameras
+	if [[ $numcolors -gt 16 ]]; then
+	imoptions+=" -shadow "		# Just for fun :-)
+	fi
 
-    # See top of this file to change fontfamily and fontsize.
-    [[ "$fontfamily" ]]  &&  imoptions+=" -font $fontfamily "
-    [[ "$fontsize" ]] &&     imoptions+=" -pointsize $fontsize "
+	# See top of this file to change fontfamily and fontsize.
+	[[ "$fontfamily" ]]  &&  imoptions+=" -font $fontfamily "
+	[[ "$fontsize" ]] &&     imoptions+=" -pointsize $fontsize "
 
-    # Create and display montages one row at a time.
-    while [ $# -gt 0 ]; do
-        # While we still have images to process...
-    onerow=()
-    goal=$(($# - numtiles)) # How many tiles left after this row
-    while [ $# -gt 0  -a  $# -gt $goal ]; do
-        len=${#onerow[@]}
-        onerow[len++]="-label"
-        onerow[len++]=$(processlabel "$1")
-        onerow[len++]="$1"
-        shift
-    done
-    montage "${onerow[@]}"  $imoptions gif:-  \
-        | magick - -colors $numcolors sixel:-
-    done
+	# Create and display montages one row at a time.
+	while [ $# -gt 0 ]; do
+		# While we still have images to process...
+	onerow=()
+	goal=$(($# - numtiles)) # How many tiles left after this row
+	while [ $# -gt 0  -a  $# -gt $goal ]; do
+		len=${#onerow[@]}
+		onerow[len++]="-label"
+		onerow[len++]=$(processlabel "$1")
+		onerow[len++]="$1"
+		shift
+	done
+	montage "${onerow[@]}"  $imoptions gif:-  \
+		| magick - -colors $numcolors sixel:-
+	done
 }
 
 processlabel() {
-    # This routine is all about appeasing ImageMagick.
-    # 1. Remove silly [0] suffix. Quote percent backslash, and at sign.
-    # 2. Replace control characters with question marks.
-    # 3. If a filename is too long, remove extension (.jpg).
-    # 4. Split long filenames with newlines (recursively)
-    span=45			# filenames longer than span will be split
-    echo -n "$1" |
-    $SED 's|\[0]$||;' | tr '[:cntrl:]' '?' |
-    awk -v span=$span -v ORS=""  '
-    function halve(s,      l,h) { 	# l and h are locals
-        l=length(s);  h=int(l/2);
-        if (l <= span) { return s; }
-        return halve(substr(s, 1, h))  "\n"  halve(substr(s, h+1));
-    }
-    {
-      if ( length($0) > span ) gsub(/\..?.?.?.?$/, "");
-      print halve($0);
-        }
-        ' |
-    $SED 's|%|%%|g; s|\\|\\\\|g; s|@|\\@|g;'
+	# This routine is all about appeasing ImageMagick.
+	# 1. Remove silly [0] suffix. Quote percent backslash, and at sign.
+	# 2. Replace control characters with question marks.
+	# 3. If a filename is too long, remove extension (.jpg).
+	# 4. Split long filenames with newlines (recursively)
+	span=45			# filenames longer than span will be split
+	echo -n "$1" |
+	$SED 's|\[0]$||;' | tr '[:cntrl:]' '?' |
+	awk -v span=$span -v ORS=""  '
+	function halve(s,      l,h) { 	# l and h are locals
+		l=length(s);  h=int(l/2);
+		if (l <= span) { return s; }
+		return halve(substr(s, 1, h))  "\n"  halve(substr(s, h+1));
+	}
+	{
+	  if ( length($0) > span ) gsub(/\..?.?.?.?$/, "");
+	  print halve($0);
+		}
+		' |
+	$SED 's|%|%%|g; s|\\|\\\\|g; s|@|\\@|g;'
 }
 
 ####
diff --git a/bin/reformat_spaces_to_tabs b/bin/reformat_spaces_to_tabs
--- a/bin/reformat_spaces_to_tabs
+++ b/bin/reformat_spaces_to_tabs
@@ -8,81 +8,217 @@
 # run: `tabs -2` (or whatever width you want), possibly in your dotfiles.
 
 # is AWK set to anything? If not, prefer frawk, then gawk, then awk
-[ -z "${AWK}" ] && export AWK=$(command -v frawk || command -v gawk || command -v awk)
+# [ -z "${AWK}" ] && export AWK=$(command -v frawk || command -v gawk || command -v awk)
 
 reformat_spaces_to_tabs() {
+	local AWK=$(command -v gawk || command -v awk)
 	[ -n "${EDIT}" ] && unset EDIT && edit_function "${FUNCNAME[0]}" "$BASH_SOURCE" && return
+	
+	# Parse arguments
+	local in_place=false
+	local files=()
+	
+	# Process arguments
+	while [[ $# -gt 0 ]]; do
+		case "$1" in
+			-i|--in-place)
+				in_place=true
+				shift
+				;;
+			*)
+				# Check if file exists
+				if [ -f "$1" ]; then
+					# Check if it's a text file
+					if file -b --mime-type "$1" | grep -q "^text/"; then
+						files+=("$1")
+					else
+						echo "Warning: Not a text file: $1" >&2
+					fi
+				else
+					echo "Warning: File not found: $1" >&2
+				fi
+				shift
+				;;
+		esac
+	done
+	
+	# If no files provided, show usage
+	if [ ${#files[@]} -eq 0 ]; then
+		echo "Usage: reformat_spaces_to_tabs [-i|--in-place] file1 [file2 ...]"
+		echo "  -i, --in-place    Modify files in place instead of printing to stdout"
+		return 1
+	fi
+	
+	# Process each file
+	for file in "${files[@]}"; do
+		_process_file "$file" "$in_place"
+	done
+}
+
+# Helper function to process a single file
+_process_file() {
 	local file="$1"
+	local in_place="$2"
+	
+	# Double-check that it's a text file (in case this function is called directly)
+	if ! file -b --mime-type "$file" | grep -q "^text/"; then
+		echo "Error: Not a text file: $file" >&2
+		return 1
+	fi
 	function determine_tab_size_in_spaces() {
 		$AWK '
 			{
-				# Match the leading spaces and count the occurrences
-				match($0, /^ */);
-				indents[RLENGTH]++;
-			}
-			END {
-				# Find the 3 most common indentation levels
-				max_count = 0;
-				max_indent = 0;
-				second_max_indent = 0;
-				third_max_indent = 0;
-				for (indent in indents) {
-					if (indents[indent] > max_count && indent > 0) {
-						third_max_indent = second_max_indent;
-						second_max_indent = max_indent;
-						max_indent = indent;
-						max_count = indents[indent];
+				# Skip empty lines and lines without leading spaces
+				if (length($0) > 0 && ($0 ~ /^ / || $0 ~ /^\t/)) {
+					# Match the leading spaces and tally the occurrences
+					match($0, /^ */);
+					if (RLENGTH > 0) {
+						space_indents[RLENGTH]++;
+					}
+					# Match the leading tabs and tally the occurrences
+					match($0, /^\t*/);
+					if (RLENGTH > 0) {
+						tab_indents[RLENGTH]++;
 					}
 				}
-				# Determine what the greatest common divisor is for the most common indentation levels,
-				# handling up to 8 spaces (which is what my terminal outputs, which is ridiculous)
-				if (max_indent % 8 == 0 && second_max_indent % 8 == 0 && third_max_indent % 8 == 0) {
-					print 8;
-				} else if (max_indent % 7 == 0 && second_max_indent % 7 == 0 && third_max_indent % 7 == 0) {
-					print 7;
-				} else if (max_indent % 6 == 0 && second_max_indent % 6 == 0 && third_max_indent % 6 == 0) {
-					print 6;
-				} else if (max_indent % 5 == 0 && second_max_indent % 5 == 0 && third_max_indent % 5 == 0) {
-					print 5;
-				} else if (max_indent % 4 == 0 && second_max_indent % 4 == 0 && third_max_indent % 4 == 0) {
-					print 4;
-				} else if (max_indent % 3 == 0 && second_max_indent % 3 == 0 && third_max_indent % 3 == 0) {
-					print 3;
-				} else if (max_indent % 2 == 0 && second_max_indent % 2 == 0 && third_max_indent % 2 == 0) {
-					print 2;
-				} else if (max_indent == 0) {
+			}
+			END {
+				# Find the 3 most common indentation levels of tabs and spaces
+				max_count_spaces = 0;
+				max_count_tabs = 0;
+				max_indent_spaces = 0;
+				max_indent_tabs = 0;
+				second_max_indent_spaces = 0;
+				second_max_indent_tabs = 0;
+				third_max_indent_spaces = 0;
+				third_max_indent_tabs = 0;
+				
+				# Sort space indents by frequency to find top 3
+				for (indent in space_indents) {
+					if (space_indents[indent] > max_count_spaces && indent > 0) {
+						third_max_indent_spaces = second_max_indent_spaces;
+						second_max_indent_spaces = max_indent_spaces;
+						max_indent_spaces = indent;
+						max_count_spaces = space_indents[indent];
+					}
+				}
+				
+				# Sort tab indents by frequency to find top 3
+				for (indent in tab_indents) {
+					if (tab_indents[indent] > max_count_tabs && indent > 0) {
+						third_max_indent_tabs = second_max_indent_tabs;
+						second_max_indent_tabs = max_indent_tabs;
+						max_indent_tabs = indent;
+						max_count_tabs = tab_indents[indent];
+					}
+				}
+				
+				# Debug output to help with troubleshooting
+				# printf "Found space indents: %d, %d, %d\n", max_indent_spaces, second_max_indent_spaces, third_max_indent_spaces > "/dev/stderr";
+				# printf "Found tab indents: %d, %d, %d\n", max_indent_tabs, second_max_indent_tabs, third_max_indent_tabs > "/dev/stderr";
+				
+				# If tabs are more common than spaces, return 0
+				if (max_count_tabs > max_count_spaces) {
+					print "Tabs are more common than spaces in file '$1'" > "/dev/stderr";
 					print 0;
-				} else {
-					print 1;
+				}
+				else {
+					# Determine what the greatest common divisor is for the most common indentation levels
+					# This filters out oddball indentations that would throw off the calculation
+					if (max_indent_spaces % 8 == 0 && second_max_indent_spaces % 8 == 0 && third_max_indent_spaces % 8 == 0) {
+						print 8;
+					} else if (max_indent_spaces % 7 == 0 && second_max_indent_spaces % 7 == 0 && third_max_indent_spaces % 7 == 0) {
+						print 7;
+					} else if (max_indent_spaces % 6 == 0 && second_max_indent_spaces % 6 == 0 && third_max_indent_spaces % 6 == 0) {
+						print 6;
+					} else if (max_indent_spaces % 5 == 0 && second_max_indent_spaces % 5 == 0 && third_max_indent_spaces % 5 == 0) {
+						print 5;
+					} else if (max_indent_spaces % 4 == 0 && second_max_indent_spaces % 4 == 0 && third_max_indent_spaces % 4 == 0) {
+						print 4;
+					} else if (max_indent_spaces % 3 == 0 && second_max_indent_spaces % 3 == 0 && third_max_indent_spaces % 3 == 0) {
+						print 3;
+					} else if (max_indent_spaces % 2 == 0 && second_max_indent_spaces % 2 == 0 && third_max_indent_spaces % 2 == 0) {
+						print 2;
+					} else if (max_indent_spaces == 0) {
+						print 0;
+					} else {
+						# Default to smallest indent if no pattern found
+						print 1;
+					}
 				}
 			}
 		' "$1"
 	}
 	local indent=$(determine_tab_size_in_spaces "$file")
+	
+	# Debug output to help troubleshoot indent detection
+	# echo "Detected indent size: $indent for $file" >&2
+
 	if (( indent > 0 )); then
-		# >&2 echo "Indent size: $indent"
 		indent_spaces=$(printf "%${indent}s")
-		$AWK -v indent="$indent_spaces" '
-		{
-			while (match($0, "^\t*"indent)) {
-				$0 = gensub("^(\t*)"indent, "\\1\t", "g");
-			}
-			print;
-		}' "$file" #> "$file.tmp" && mv "$file.tmp" "$file"
+		if [ "$in_place" = "true" ]; then
+			# Create a backup of the original file
+			local backup_file="${file}.maybe-no-tabs"
+			cp -p "$file" "$backup_file"
+			
+			# Save file permissions (cross-platform compatible)
+			local STAT=$(command -v gstat || command -v stat)
+			local stat_format="%a"
+			# Check if we're on macOS (BSD stat)
+			if [[ "$OSTYPE" == "darwin"* ]] && [[ "$STAT" == *"/stat" ]]; then
+				stat_format="-f %A"
+				local file_perms=$($STAT $stat_format "$file")
+			else
+				local file_perms=$($STAT -c "%a" "$file")
+			fi
+			
+			# Process in-place
+			$AWK -v indent="$indent_spaces" '
+			{
+				while (match($0, "^\t*"indent)) {
+					$0 = gensub("^(\t*)"indent, "\\1\t", "g");
+				}
+				print;
+			}' "$file" > "$file.new"
+			
+			# Apply original permissions to the new file
+			chmod "$file_perms" "$file.new"
+			
+			# Replace the original file
+			mv "$file.new" "$file"
+			echo "Reformatted: $file (indent size: $indent)"
+		else
+			# Output to stdout
+			$AWK -v indent="$indent_spaces" '
+			{
+				while (match($0, "^\t*"indent)) {
+					$0 = gensub("^(\t*)"indent, "\\1\t", "g");
+				}
+				print;
+			}' "$file"
+		fi
 	else
 		# >&2 echo "Indent size: 0"
-		cat "$file"
+		if [ "$in_place" = "true" ]; then
+			echo "No changes needed for: $file"
+		else
+			cat "$file"
+		fi
 	fi
 }
 
 # Export the function so it can be used by find -exec
-export -f reformat_spaces_to_tabs
 
 # Run the function, passing along any args, if this file was run directly (such as via sudo) instead of as an include
 # Sometimes, $0 contains a leading dash to indicate an interactive (or is it login?) shell,
 # which is apparently an old convention (which also broke the basename call on OS X)
-_me=$(basename "${0##\-}")
-if [ "$_me" = "reformat_spaces_to_tabs" ]; then
-	$_me "$@"
+if ! (return 0 2>/dev/null); then
+  # Check if we are running tests
+  if [ "$1" = "--test" ]; then
+    # Run tests from the test file
+    . "$HOME/dotfiles/bin/test/$(basename "${0##\-}")_test"
+  else
+    # If called directly, pass all arguments to the function
+    $(basename "${0##\-}") "$@"
+  fi
 fi
-unset _me
